__author__ = 'Giovanni'

from utilities_point import FtnPoint
from PySide import QtCore, QtGui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 265)
        MainWindow.setMinimumSize(QtCore.QSize(320, 265))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 298, 206))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtX1 = QtGui.QLineEdit(self.widget)
        self.txtX1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtX1.setObjectName("txtX1")
        self.gridLayout.addWidget(self.txtX1, 1, 1, 1, 1)
        self.txtX2 = QtGui.QLineEdit(self.widget)
        self.txtX2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtX2.setObjectName("txtX2")
        self.gridLayout.addWidget(self.txtX2, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtY2 = QtGui.QLineEdit(self.widget)
        self.txtY2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtY2.setObjectName("txtY2")
        self.gridLayout.addWidget(self.txtY2, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.txtZ1 = QtGui.QLineEdit(self.widget)
        self.txtZ1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtZ1.setObjectName("txtZ1")
        self.gridLayout.addWidget(self.txtZ1, 3, 1, 1, 1)
        self.txtZ2 = QtGui.QLineEdit(self.widget)
        self.txtZ2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtZ2.setObjectName("txtZ2")
        self.gridLayout.addWidget(self.txtZ2, 3, 2, 1, 1)
        self.txtY1 = QtGui.QLineEdit(self.widget)
        self.txtY1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtY1.setObjectName("txtY1")
        self.gridLayout.addWidget(self.txtY1, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.btnCalcola = QtGui.QPushButton(self.widget)
        self.btnCalcola.setObjectName("btnCalcola")
        self.verticalLayout.addWidget(self.btnCalcola)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.txtDistanza = QtGui.QLineEdit(self.widget)
        self.txtDistanza.setObjectName("txtDistanza")
        self.horizontalLayout.addWidget(self.txtDistanza)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.txtAngolo = QtGui.QLineEdit(self.widget)
        self.txtAngolo.setObjectName("txtAngolo")
        self.horizontalLayout_2.addWidget(self.txtAngolo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Distanza / Angolo", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Punto 1 :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Punto 2 :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "X : ", None, QtGui.QApplication.UnicodeUTF8))
        self.txtX1.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.txtX2.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Y : ", None, QtGui.QApplication.UnicodeUTF8))
        self.txtY2.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Z : ", None, QtGui.QApplication.UnicodeUTF8))
        self.txtZ1.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.txtZ2.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.txtY1.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCalcola.setText(QtGui.QApplication.translate("MainWindow", "Calcola", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Distanza :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Angolo : ", None, QtGui.QApplication.UnicodeUTF8))

class FinestraDiDialogo(QtGui.QMainWindow):
    def __init__(self, parent=None):
        super(FinestraDiDialogo, self).__init__(parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.btnCalcola.clicked.connect(self.calcola)

    def calcola(self):
        x1 = float(self.ui.txtX1.text())
        y1 = float(self.ui.txtY1.text())
        z1 = float(self.ui.txtZ1.text())
        x2 = float(self.ui.txtX2.text())
        y2 = float(self.ui.txtY2.text())
        z2 = float(self.ui.txtZ2.text())
        calcolatore = FtnPoint(punto1=[x1, y1, z1], punto2=[x2, y2, z2])
        self.ui.txtDistanza.setText(unicode(calcolatore.distanza))
        self.ui.txtAngolo.setText(unicode(calcolatore.angoloXY))

app = QtGui.QApplication.instance()

if not app:
    app = QtGui.QApplication([])

mainWindow = FinestraDiDialogo()
mainWindow.show()
app.exec_()